### ISSUE TITLE
Corrections on Chinese_simp.lang

### ISSUE THREAD

**Issue by VielamChalis** [NiclqsGER/wolfpack-localization#14]
**THAT PERSON USED MACHINE TRAINSLATION : (**

### Corrections:

"pairs": 

"key": 0,
"value": "未缓存"

"key": 6,
"value": "开"

"key": 14,
"value": "否"

"key": 69,
"value": "地图线段透明度"

"key": 118,
"value": "任务简报"

"key": 142,
"value": "快速发现"

"key": 154,
"value": "遭遇战"

"key": 212,
"value": "莫尔斯电键输入"

"key": 252,
"value": "打开/关闭距离对照表"

"key": 253,
"value": "切换距离对照表类型（垂直/水平）"

"key": 254,
"value": "增加距离对照表数值1米"

"key": 255,
"value": "减少距离对照表数值1米"

"key": 256,
"value": "增加距离对照表数值10米"

 "key": 257,
"value": "减少距离对照表数值10米"

"key": 261,
"value": "成员组配置"

"key": 263,
"value": "离开成员组"

"key": 264,
"value": "加入成员组"

"key": 266,
"value": "成员组已满"

"key": 270,
"value": "成员组选项"

"key": 271,
"value": "封禁名单选项"

### Other translations choice

    "morsePairs": [
        {
            "key": 0,
            "value": "尝试呼叫"
        },
        {
            "key": 1,
            "value": "选择频率"
        },
        {
            "key": 9,
            "value": "完毕"
        },
        {
            "key": 2,
            "value": "收到"
        },
        {
            "key": 3,
            "value": "信息确认"
        },
        {
            "key": 4,
            "value": "请重复"
        },
        {
            "key": 5,
            "value": "等待"
        },
        {
            "key": 6,
            "value": "切出"
        },
        {
            "key": 7,
            "value": "同意"
        },
        {
            "key": 8,
            "value": "否决"
        },
        {
            "key": 10,
            "value": "信息开头"
        },
        {
            "key": 11,
            "value": "信息结尾"
        }
    ]

**Comment by niclqs** [comment]
Hello,
I will add your improvement in the course of the day [UTC+1 :)]

**Comment by niclqs** [comment]
Merged already
