### ISSUE TITLE
Translations German

### ISSUE THREAD

**Issue by NextTomShark** [NiclqsGER/wolfpack-localization#2]
ZENTRALE
depth meter - Tiefenmesser
m water over keel - m Wasser über Kiel
navigation chart - Navigationskarte
turn on bilge pump - Bildgepumpe starten
open/close door - Kugelschott öffnen/schließen
night light switch - Rotlicht Schalter 
intercom - Bordsprechanlage
intercom: select station - Abteilung wählen
open lid - Abdeckung öffnen
alarm - Alarm
ladder - Leiter
negative tank controls - Untertriebszelle Handrad
trim tank controls - Trimmzellen Handrad
dive controls  - Tiefenruderstand
forward/aft ballast vent - Vorderes/Hinteres Tauchtankventil
helm station- Steuerstand / Ruderstand
raise periscope - Periskop ausfahren 
echo ranger - Echolot

FUNK/HYDROPHON
radioman - Funker (Funkschapp)
turn page - Umblättern/Nächste Seite
Enigma machine - Enigma Chiffriermaschine /  Enigma Schlüsselmaschine
radio transceiver - Funksendeempfänger
radio direction finder - Funkmeßbeobachtungsgerät
raise direction finder antenna - Funkmeßantenne ausfahren
record player - Grammophon

hydrophone - Hydrophon (Horchschapp)
opterator - Horcher
high pass - Hochpassfilter
low pass - Tiefpassfilter
gain - Pegel
volume - Lautstärke
hydrophone direction - (Horch)Peilung

  "header": "Community (AI) German",
  "pairs": [
    {
      "key": -1,
      "value": "INVALID"
"value": "UNGÜLTIG"
    },
    {
      "key": 25,
      "value": "Kredite"
"value": "Credits"
    },
    {
      "key": 26,
      "value": "Beenden Sie"
"value": "Beenden"
    },
    {
      "key": 9,
      "value": "Behinderte"
"value": "Deaktiviert"
    },
    {
      "key": 12,
      "value": "Jede"
"value": "Alle"
    },
    {
      "key": 2,
      "value": "Verlassen Sie"
  "value": "Verlassen"
    },
    {
      "key": 36,
      "value": "Effekte Volumen"
  "value": "Effekte Lautstärke"
    },
    {
      "key": 37,
      "value": "VOIP-Volumen"
"value": "VOIP Lautstärke"
    },
    {
      "key": 38,
      "value": "Benutzeroberfläche Volumen"
"value": "Benutzeroberfläche Lautstärke"
    },
    {
      "key": 43,
      "value": "Auflösung des Spiels"
 "value": "Spiel beenden"
    },
    {
      "key": 47,
      "value": "Auflösung der Textur"
"value": "Texturqualität"
    },
    {
      "key": 48,
      "value": "Anisotrope Filterung"
"value": "Anisotropischer Filter"
    },
    {
      "key": 50,
      "value": "Exklusiver Vollbildschirm"
"value": "Vollbildschirm"
    },
    {
": 54,
      "value": "Jeder Rahmen"
"value": "Jeder Frame"
    },
    {
      "key": 55,
      "value": "Jeder zweite Rahmen"
"value": "Jeder zweite Frame"
    },
    {
      "key": 56,
      "value": "Unter"
"value": "Aus"
    },
    {
      "key": 64,
      "value": "Empfindlichkeit der Kameradrehung"
"value": "Kameraempfindlichkeit"
    },
    {
      "key": 66,
      "value": "Intensität des Scrollrads"
"value": "Scrollrad Geschwindigkeit"
    },
    {
      "key": 68,
      "value": "Umgekehrte Maus"
"value": "Maus invertieren"
    },
    {
      "key": 69,
      "value": "Karte Linienmaßstab"
"value": "Kartenmaßstab"
    },
    {
      "key": 70,
      "value": "Karte Schriftart Maßstab"
"value": "Schriftgröße Karte"
    },
    {
      "key": 71,
      "value": "Namensschilder anzeigen"
"value": "Bootsnamen anzeigen"
    },
    {
      "key": 73,
      "value": "Bildfrequenzzähler anzeigen"
"value": "Framrateanzeigen"
    },
    {
      "key": 75,
      "value": "Kameraausschlag aktivieren"
"value": "Sichtstabilisierung aktivieren"
    },
    {
      "key": 77,
      "value": "Menü Hintergrund Deckkraft"
"value": "Hintergrundtransparenz"
    },
    {
      "key": 79,
      "value": "Wasserspray Partikelanzahl"
"value": "Partikelanzahl Wasser"
"value": "Partikelanzahl Gischt"
    },
    {
      "key": 80,
      "value": "Dynamische Schaumstoffqualität"
"value": "Dynamische Schaumkronenqualität"
    },
    {
      "key": 82,
      "value": "Bildschirmraum Ambient Occlusion"
  "value": "Umgebungsverdeckung"
    },
    {
      "key": 83,
      "value": "Bildschirmraum Reflexion"
"value": "Screen Space Reflections"
    },
    {
      "key": 85,
      "value": "Blüte"
"value": "Bloom"
    },
    {
      "key": 86,
      "value": "Helligkeitskorrektur"
    },
    {
      "key": 92,
      "value": "Sprachen nachladen"
"value": "Sprachen laden"
    },
    {
      "key": 97,
      "value": "Lobby Entfernung"
"value": "Lobby Standort"
    },
    {
      "key": 102,
      "value": "Lässig"
"value": "EWinfach"
    },
    {
      "key": 105,
      "value": "Schließen Sie"
 "value": "Schließen"
    },
    {
      "key": 119,
      "value": "Schwierigkeitsgrad-Einstellungen"
"value": "Schwierigkeitsgrad"
    },
    {
      "key": 121,
      "value": "Bestellungen"
"value": "Befehle"

      "key": 131,
      "value": "Zeit des Tages"
"value": "Tageszeit"
    },
    {
      "key": 140,
      "value": "Vereinfachtes Radio"
"value": "Vereinfachter Funk"
    },
    {
      "key": 144,
      "value": "Konvoi ändert periodisch die Richtung"
"value": "Konvoi ändert periodisch den Kurs"
    },
    {
      "key": 146,
      "value": "Eskorte Verfolgungszeit"
"value": "Verfolgungszeit durch Eskorten"
    },
    {
      "key": 149,
      "value": "Defekte Torpedos"
"value": "Torpedoblindgänger"
    },
    {
      "key": 151,
      "value": "Torpedoauslösung ist winkelabhängig"
"value": "Torpedoaufschlagzünder ist winkelabhängig"
    },
    {
      "key": 154,
      "value": "Scharmützel"
"value": "Gefecht"
    },
    {
      "key": 158,
      "value": "Norwegisches Meer"
"value": "Nordmeer"

      "key": 173,
      "value": "Torpedos treffen"
"value": "Torpedotreffer"
    },
    {
      "key": 175,
      "value": "Zerstörte Kaufleute"
"value": "Versenkte Handelsschiffe"
    },
    {
      "key": 176,
      "value": "Zerstörte Kriegsschiffe"
"value": "Versenkte Kriegsschiffe"
    },
    {
      "key": 178,
      "value": "Mission Zeit"
 "value": "Missionszeit"
    },
    {
      "key": 201,
      "value": "Feuer-Torpedo"
 "value": "Torpedo abfeuern"
    },
    {
      "key": 202,
      "value": "Untere Vorwärts-Tauchflugzeuge"
"value": "Vorderes Tiefenruder unten"
"value": "Vorderes Tiefenruder nach unten"
    },
    {
      "key": 203,
      "value": "Vorwärts-Tauchflugzeuge anheben"
"value": "Vorderes Tiefenruder oben"
"value": "Vorderes Tiefenruder nach oben"
    },
    {
      "key": 204,
      "value": "Untere Achter-Tauchflugzeuge"
"value": "Achteres Tiefenruder unten"
"value": "Achteres Tiefenruder nach unten"
    },
    {
      "key": 205,
      "value": "Achter-Tauchflugzeuge anheben"
"value": "Achteres Tiefenruder oben"
"value": "Achteres Tiefenruder nach oben"
    },
    {
      "key": 206,
      "value": "Taschenlampe umschalten"
    },
    {
      "key": 207,
      "value": "Toggle Recognition Handbuch"
"value": "Erkennungshandbuch umschalten"
    },
    {
      "key": 210,
      "value": "Center Forward Diveplane"
"value": "Vorderes Tiefenruder mittig"
"value": "Vorderes Tiefenruder Mitte"
    },
    {
      "key": 211,
      "value": "Zentrum-Achtern-Tauchflugzeug"
"value": "Hinteres Tiefenruder mittig"
"value": "Hinteres Tiefenruder Mitte"
    },
    {
      "key": 213,
      "value": "Morsezeichen Single Dot"
"value": "Morsezeichen "Kurz""
    },
    {
      "key": 214,
      "value": "Morsezeichen Einfacher Strich"
"value": "Morsezeichen "Lang""
    },
    {
      "key": 215,
      "value": "Kontinuierliche Morsepunkte"
"value": "Kontinuierlich Kurz"
    },
    {
      "key": 216,
      "value": "Kontinuierliche Morsestriche" 
"value": "Kontinuierlich Lang"
    },
    {
      "key": 217,
      "value": "Nächste Morse-Text-Seite"
"value": "Nächste Seite"
    },
    {
      "key": 218,
      "value": "Vorherige Morse-Text-Seite"
"value": "Vorherige Seite"
    },
    {
      "key": 219,
      "value": "Stumme Stimme"
"value": "Stumm schalten"
    },
    {
      "key": 220,
      "value": "Bot Menü Toggle"
"value": "Bot Menü umschalten"   
    },
    {
      "key": 224,
      "value": "Karte Kilometerzähler zurücksetzen"
"value": "Kilometerzähler zurücksetzen"
    },
    {
      "key": 225,
      "value": "Kartensymbol-Werkzeug"
"value": "Markierung"
    },
    {
      "key": 226,
      "value": "Kartenlinien-Werkzeug"
"value": "Lineal"
    },
    {
      "key": 227,
      "value": "Karte Kreis Werkzeug"
"value": "Kompass"
    },
    {
      "key": 228,
      "value": "Map Write Tool"
"value": "Beschriftung"
"value": "Notizen"
    },
    {
      "key": 229,
      "value": "Karte kopieren Linie Werkzeug"
"value": "kopieren"
    },
    {
      "key": 230,
      "value": "Map Eraser Tool"
"value": "Radiergummi"
    },
    {
      "key": 231,
      "value": "Kartenwinkelmesser-Werkzeug"
"value": "Winkelmesser"
    },
    {
      "key": 232,
      "value": "Karte Quicktool Symbol"
"value": "Quicktool Symbol"
    },
    {
      "key": 233,
      "value": "Karte Quicktool Line"
"value": "Quicktool Linie"
    },
    {
      "key": 234,
      "value": "Karte Quicktool Kreis"
"value": "Quicktool Kreis"
    },
    {
      "key": 235,
      "value": "Karte Quicktool Zeile kopieren"
 "value": "Quicktool Zeile kopieren"
    },
    {
      "key": 236,
      "value": "Karte Quicktool Radierer"
"value": "Quicktool Radierer"
    },
    {
      "key": 237,
      "value": "Karte Quicktool Winkelmesser"
"value": "Quicktool Winkelmesser"
    },
    {
      "key": 240,
      "value": "Karte Toggle Umgekehrter Kompass"
"value": "Kompassausrichtung umschalten"
    },
    {
      "key": 241,
      "value": "Karte Zeitmodus umschalten"
"value": "Zeitmodus umschalten"
    },
    {
      "key": 242,
      "value": "Karte Toggle Winkel anzeigen"
"value": "Winkel anzeigen"
    },
    {
      "key": 244,
      "value": "Karte Toggle Entfernung anzeigen"
"value": "Entfernung anzeigen"
    },
    {
      "key": 245,
      "value": "Karte Toggle-Symbol"
"value": "Symbole anzeigen"
    },
    {
      "key": 246,
      "value": "Karte zurücksetzen Drehung des Winkelmessers"
"value": "Winkelmessers zurücksetzen"
    },
    {
      "key": 247,
      "value": "Map Toggle Draw From Midpoint"
"value": "Von Kartenmitte zeichen"
 },
    {
      "key": 250,
      "value": "Karte Toggle Winkelmesser anzeigen"
"value": "Winkelmesser anzeigen"
    },
    {
      "key": 258,
      "value": "Periskop-Helligkeit erhöhen"
"value": "Helligkeit erhöhen"
    },
    {
      "key": 266,
      "value": "Besatzung ist voll"
"value": "Besatzung ist vollständig"
    },
    {
      "key": 298,
      "value": "Senden Sie"
"value": "Senden"
    },
    {
      "key": 299,
      "value": "Speichern Sie"
"value": "Speichern"
    },
    {
      "key": 301,
      "value": "Sendung"
"value": "Übertragung"
    },
    {
      "key": 2,
      "value": "Roger"
"value": "Verstanden"
    },
    {
      "key": 4,
      "value": "Wiederholen Sie"
"value": "Wiederholen"

**Comment by niclqs** [comment]
**GitHub Commit:**

- **Commit:** [e01167b](https://github.com/NiclqsGER/wolfpack-localization/commit/e01167b91bc6b4a23c5a4de62be6dffeda7d97b9)
- **Date:** 30.12.2023 - 18:55

---

Appreciate your issue report and collaboration. Merged your translation with other suggestions; potential new errors. Keeping the issue open for further improvements. Feel free to post suggestions. Download the latest version [here](https://github.com/NiclqsGER/wolfpack-localization/releases). Thanks for your support!

**Comment by niclqs** [comment]
I'm closing this post for the sake of clarity. For new problems, simply open a new issue
